// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Todo struct {
	TodoID      pgtype.UUID
	ClerkID     string
	Title       string
	Description *string
	Status      string
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}
