// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTodoByUid = `-- name: GetTodoByUid :many
SELECT todos.todo_id, todos.user_id, todos.title, todos.description, todos.status, todos.created_at, todos.updated_at
FROM todos
WHERE user_id = $1
`

func (q *Queries) GetTodoByUid(ctx context.Context, userID pgtype.UUID) ([]Todo, error) {
	rows, err := q.db.Query(ctx, getTodoByUid, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.TodoID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
